### ISSUE TITLE
Install via ports, but fox16 gem not found

### ISSUE THREAD

**Issue by simonszu** [lylejohnson/fxruby#2]
I have installed fxruby as described in the wiki via macports. Trying to require the fox16 gem, ruby has an error:

/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- fox16 (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from ./ttwtr.rb:8

Then i tried to install the fx gem manually as described in the manual section (i thought the mac port forgot it somehow), and i got this error:

sudo gem install fxruby
ERROR:  While executing gem ... (Gem::Exception)
    ruby_code case not handled: Regexp

After this, i get an error, everytime my bash prompt returns:
[/Library/Ruby/Gems/1.8/specifications/fxruby-1.6.20-universal-darwin-10.gemspec] isn't a Gem::Specification (NilClass instead).

I removed this file, and everything was fine, but i can't use Fxruby either. 

Mac OS X 10.6

**Comment by dccmmtop** [comment]
I meet the same problem,,
