### ISSUE TITLE
fox16.so: undefined symbol: rb_thread_pending

### ISSUE THREAD

**Issue by alessioalex** [lylejohnson/fxruby#3]
I have Ubuntu 11.04.

I have done exactly what you say here: https://github.com/lylejohnson/fxruby/wiki/Setting-Up-a-Linux-Build-Environment

When I require fox16 I get this:

/home/alessio/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in `require': /home/alessio/.rvm/gems/ruby-1.9.2-p290/gems/fxruby-1.6.20-x86-linux/lib/fox16.so: undefined symbol: rb_thread_pending - /home/alessio/.rvm/gems/ruby-1.9.2-p290/gems/fxruby-1.6.20-x86-linux/lib/fox16.so (LoadError)
    from /home/alessio/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in`rescue in require'
    from /home/alessio/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /home/alessio/.rvm/gems/ruby-1.9.2-p290/gems/fxruby-1.6.20-x86-linux/lib/fox16.rb:6:in`<top (required)>'
    from internal:lib/rubygems/custom_require:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in`rescue in require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from fxruby_test.rb:3:in`<main>'

**Comment by larskanis** [comment]
This seems to be the binary Linux gem. You may use:
<tt>gem install fxruby --platform ruby</tt>

You also could test the new pre-release:
<tt>gem install fxruby --prerelease</tt>
