### ISSUE TITLE
3 seconds to require in 1.8.7, 15 in 1.9.3, why?

### ISSUE THREAD

**Issue by damian-m-g** [lylejohnson/fxruby#5]
Hello lyle, don't sure if you will read this, first of all: thanks for your effort trough the years keeping FOX GUI usable and thanks Lars Kanis for be in charge now.
 I will not botter writing what was writed, please take a look at this topic I've opened:

 http://www.ruby-forum.com/topic/4402652#new

 Cheers.

**Comment by lylejohnson** [comment]
Igor,

I have not been involved with FXRuby for quite awhile now. Best advice is to post your question to the fxruby-users mailing list. 

Good luck!

**Comment by damian-m-g** [comment]
Ok! you should quit out the link to this page(or change to Lars meaby?)from RubyGems.org. It become from "Bug Report". See ya'!

**Comment by larskanis** [comment]
Hi Igor,

on my old Athlon-64 running Ubuntu 12.04 loading times are quite fast (at least after loading it once in the cache):

```
1.8.7 :001 > Benchmark.realtime { require 'fox16' }
 => 0.681920051574707 

1.9.3p0 :001 > Benchmark.realtime { require 'fox16' }
 => 0.349081972 
```

so it seems to be an issue on Windows, only? I'll have a look on it at the weekend.

**Comment by larskanis** [comment]
I'm able to reproduce the issue. Loading times for 1.9 are over 10 seconds on an older PC with WinXP and around 3 seconds on a modern running Win-7. A little bit less, when using 1.8.7. The delay is while loading the fox16.so, even if all code is commented out from the Init section. It results in 100% kernel CPU usage, without any noticeable file access monitored with Filemon.

So I changed the compiler toolchain away from the mingw-1.0+20110523-1build2 and gcc-4.6.1 of Ubuntu 11.10. The issue disappears when using the old mingw32 toolkit with gcc-4.2.1 and is also disappears when using mingw-w64-2.0.1-1 with gcc-4.6.3 of Ubuntu 12.04. Using the latter one, require 'fox16' takes less than a second for me. With mingw32 loading takes around one second.

Please test the new gem, built with mingw-w64-2.0.1-1 with gcc-4.6.3 of Ubuntu 12.04, I've uploaded just now:

```
gem install fxruby --pre
```

If that solves your issue, I'll switch the compiler used for fxruby windows binary releases.

**Comment by damian-m-g** [comment]
That's correct Lars, it takes 1 second to be required on Windows XP SP3 platform. So the problem was in the compiler, thanks a lot for the quickly fix.

**Comment by larskanis** [comment]
As suggested by Igor, the bugtracker link in rubygems.org is changed to https://github.com/larskanis/fxruby/issues , now. So we start with a library that has never had a bug!
