### ISSUE TITLE
posibly [BUG] Segmentation fault when exit the main loop

### ISSUE THREAD

**Issue by damian-m-g** [lylejohnson/fxruby#6]
Hello, this happens when you exit the main loop(close application by the x button or by right click >> close in the toolbar of a Windows SP3 OS).
This is the code who generate it, be aware that it happen only when I use FXSplashWindow:
# Observe that this is optimized for show the logo as quickly is possible, anyway I've tried many ways of show the splash window(and what is next), and every time the BUG arise.

require 'fox16'
include Fox

if **FILE** == $0
  FXApp.new('X, 'X') do |app|
    #With and without disabling threads support fails
    app.disableThreads
    logo = Fox::FXSplashWindow.new(app, Fox::FXBMPIcon.new(app, File.open('./Recursos Fijos/CAPSI Evolution logo de carga.bmp', 'rb').read), SPLASH_SIMPLE|SPLASH_OWNS_ICON)
    app.create
    logo.show(PLACEMENT_SCREEN)
    app.addTimeout(100) do
      require './Biblioteca/Mod General'
      require './Biblioteca/Mod Materiales'
      require './Biblioteca/Vis Materiales'
      require './Biblioteca/Vis Interfaz Principal.rb'
      #VenPrincipal is subclass of FXMainWindow
      v = VenPrincipal.new(app)
      v.create
      v.show(PLACEMENT_SCREEN)
      logo.destroy
    end
    app.run
  end
end

 This work fine, until I close the application, then I got this in the shell:

 C:\Archivos de programa\Aptana\Aptana Studio 3\WORKSPACE\CAPSI Evolution>ruby '.
/Biblioteca/Iniciador.rb'
./Biblioteca/Iniciador.rb: [BUG] Segmentation fault
ruby 1.9.3p194 (2012-04-20) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0002 b:0002 l:00056c d:00056c TOP

-- C level backtrace information -------------------------------------------
C:\WINDOWS\system32\ntdll.dll(KiFastSystemCallRet+0x0) [0x7c91e514]
C:\WINDOWS\system32\kernel32.dll(WaitForSingleObject+0x12) [0x7c802542]
C:\Ruby193\bin\msvcrt-ruby191.dll(rb_vm_bugreport+0xf9) [0x62e5c589]
C:\Ruby193\bin\msvcrt-ruby191.dll(rb_name_err_mesg_new+0x17a) [0x62d3a7e2]
C:\Ruby193\bin\msvcrt-ruby191.dll(rb_bug+0x2f) [0x62d3b4fb]
C:\Ruby193\bin\msvcrt-ruby191.dll(rb_check_safe_str+0x1a4) [0x62dee168]
 [0x004011e6]
C:\WINDOWS\system32\kernel32.dll(UnhandledExceptionFilter+0x1c7) [0x7c864191]

-- Other runtime information -----------------------------------------------
- Loaded script: ./Biblioteca/Iniciador.rb
- Loaded features:
  
  0 enumerator.so
  1 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/encdb.so
  2 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/iso_8859_1.so
  3 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/trans/transdb.so
  4 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
  5 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/rbconfig.rb
  6 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
  7 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
  8 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/defaults/operating_system.rb
  9 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
  10 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb
  11 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
  12 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
  13 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
  14 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
  15 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
  16 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/utf_16le.so
  17 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/trans/utf_16_32.so
  18 C:/Ruby193/lib/ruby/1.9.1/i386-mingw32/enc/trans/single_byte.so
  19 C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
  20 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/1.9
  /fox16.so
  21 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/core.rb
  22 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/dict.rb
  23 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/settings.rb
  24 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/iterators.rb
  25 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/keys.rb
  26 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/aliases.rb
  27 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/responder.rb
  28 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/timeout.rb
  29 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/chore.rb
  30 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/signal.rb
  31 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/input.rb
  32 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/accel_table.rb
  33 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/responder2.rb
  34 C:/Ruby193/lib/ruby/gems/1.9.1/gems/rubysdl-mswin32-1.9-2.1.1.1/ext/opengl
  .so
  35 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/glgroup.rb
  36 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/execute_nonmodal.rb
  37 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/version.rb
  38 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/kwargs.rb
  39 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16/exceptions_for_fxerror.rb
  40 C:/Ruby193/lib/ruby/gems/1.9.1/gems/fxruby-1.6.25.pre1-x86-mingw32/lib/fox
  16.rb
  41 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi_c.so
  42 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/platform.rb
  43 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/types.rb
  44 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/library.rb
  45 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/errno.rb
  46 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/pointer.rb
  47 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/memorypointer.rb
  48 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/struct_layout_build
  er.rb
  49 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/struct.rb
  50 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/union.rb
  51 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/managedstruct.rb
  52 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/callback.rb
  53 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/io.rb
  54 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/autopointer.rb
  55 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/variadic.rb
  56 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/enum.rb
  57 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi/ffi.rb
  58 C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.0.11/lib/ffi.rb
  59 C:/Archivos de programa/Aptana/Aptana Studio 3/WORKSPACE/CAPSI Evolution/B
  iblioteca/Mod General.rb
  60 C:/Archivos de programa/Aptana/Aptana Studio 3/WORKSPACE/CAPSI Evolution/B
  iblioteca/Mod Materiales.rb
  61 C:/Archivos de programa/Aptana/Aptana Studio 3/WORKSPACE/CAPSI Evolution/B
  iblioteca/Vis Materiales.rb
  62 C:/Archivos de programa/Aptana/Aptana Studio 3/WORKSPACE/CAPSI Evolution/B
  iblioteca/Vis Interfaz Principal.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

 If you think that this is not FXRuby error then I'll post it in ruby-lang site, just erase this, thanks!!!!

**Comment by larskanis** [comment]
It's a fxruby-bug, for sure. I can reproduce it on Linux, so I'll be able to debug it properly and will look at it in the next days.

**Comment by larskanis** [comment]
Hi Igor,

thanks for reporting this! There were actually two issues:
1. The flag SPLASH_OWNS_ICON should not be used in Ruby. The garbage collector will free the icon, so this flag causes a double free, that results in a segfault. I pushed a patch that masks out the flag, now, so that it has no effect anymore.
2. The garbage collection for FXSplashWindow did not work correctly at application exit. The object was double free'd, which results in a segfault as well. I pushed a patch that fixes it.

Please test the just uploaded fxruby-1.6.25.pre2.

**Comment by damian-m-g** [comment]
It's fixed, work fine, thank you so much!
 I will dare to make you a question related to your previous comment, please check this post, It will take you no more than one minute, I didn't have any answer since weeks... :

 http://forums.pragprog.com/forums/53/topics/10776

**Comment by larskanis** [comment]
It took me 30 minutes to register and answer :)

So I'll release 1.6.25 with the fixes applied.
