### ISSUE TITLE
gem install

### ISSUE THREAD

**Issue by robot6** [lylejohnson/fxruby#7]
I'm having problems with it installing.  

Ruby 1.9.3p0
FOX 1.6.46

Output:

local-3:Programming johns$ gem install fxruby
Building native extensions.  This could take a while...
ERROR:  Error installing fxruby:
    ERROR: Failed to build gem native extension.

```
    /Users/johns/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb
```

checking for sys/time.h... yes
checking for signal.h... yes
checking for deflate() in -lz... yes
checking for png_create_read_struct() in -lpng... yes
checking for jpeg_mem_init() in -ljpeg... yes
checking for TIFFSetErrorHandler() in -ltiff... no
checking for XftInit() in -lXft... yes
checking for XShmQueryVersion() in -lXext... yes
checking for XFindContext() in -lX11... yes
checking for glXCreateContext() in -lGL... yes
checking for gluNewQuadric() in -lGLU... yes
creating Makefile

make
compiling librb.c
librb.c: In function ‘SWIG_TypeNameComp’:
librb.c:254: warning: implicit conversion shortens 64-bit value into a 32-bit value
compiling core_wrap.cpp
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: error: unrecognized command line option ‘-Wshorten-64-to-32’
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
make: **\* [core_wrap.o] Error 1

Gem files will remain installed in /Users/local3/.rvm/gems/ruby-1.9.3-p0@rails31/gems/fxruby-1.6.25 for inspection.
Results logged to /Users/local3/.rvm/gems/ruby-1.9.3-p0@rails31/gems/fxruby-1.6.25/ext/fox16/gem_make.out

**Comment by larskanis** [comment]
It seems like this is a compiler mis-match between what was used for Ruby and C code and what's getting used for fxruby with C++ code. Maybe the solution for EventMachine on http://instantbadger.blogspot.de/2011/11/porting-rails-23-app-to-ruby-19.html is useful for you.

**Comment by larskanis** [comment]
@robot6: Is your issue solved? I would like to close it, if so.

**Comment by robot6** [comment]
no, i got laid off so i dont have that laptop any more.  Sorry.

ÞÅÔ×ÅÒÇ, 6 ÓÅÎÔÑÂÒÑ 2012 Ç. ÐÏÌØÚÏ×ÁÔÅÌØ Lars Kanis <
notifications@github.com> ÐÉÓÁÌ:

**Comment by larskanis** [comment]
That's very unfortunate. But thanks for responding.
